Algoritmo "AP1"
// Disciplina  : [Linguagem e Lógica de Programação (criacao-de-aplicacoes-e-sistemas)]
// Professor   : Franklin Portela
// Descrição   : O programa printa na tela um texto
// Autor(a)    : Matheus Vidigal
// Data atual  : 01/04/2022
Var
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Olá mundo, meu nome é Matheus Vidigal!")

Fimalgoritmo